version: "3.7"

services:
  app:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: on-failure
    command: >
      node app.js

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
